### ISSUE TITLE
Localization mechanism

### ISSUE THREAD

**Issue by jayabie** [AgoutiDev/agouti#17]
Hello Team,

Do you have or recommend any mechanism to do the translations for this software or we have to do it manually inside each `.php` file?
For example, do you have any portal like Crowdin or Transifex?

**Comment by evgip** [comment]
Hello. At the moment, the translation is carried out within the files. Integration with third-party services is not yet available.

The main recommendation is not to change the order of the lines in these files.

In the near future, it may be necessary to move the translations to a separate repository in order to carry out localization work there.

**Comment by jayabie** [comment]
Noted, can i start now or i wait a little bit more till all software functions completed?

**Comment by evgip** [comment]
@jayabie You can start translating. It is made in such a way that it is not necessary to translate all files at once. You can add one file at a time. What language do you want to translate into?

**Comment by jayabie** [comment]
Hi Dear @evgip ,

Yes i can do 1 file at time, no problem.
i will do it in Arabic, I'm good with localization, i have helped discourse, Lemmy and some other small projects to get their Arabic language for free.
so i will work on it at my free time, once you guys decided to work on the RTL, the language will be ready, and the users of RTL and Arabic will be able to use it immediately.

**Comment by evgip** [comment]
@jayabie Thank you!
