### ISSUE TITLE
Cant install it locally

### ISSUE THREAD

**Issue by greatdesign** [AgoutiDev/agouti#2]
HI I tried to install the project locally on my Lampp server but cant load it. When i visit the /public folder i get a blank page with no php errors !
Here are the steps i did:
1. I downloaded the latest release 0.1.8
2. I imported the dev.sql in my phpMyAdmin 
3. I set the credentials for the dbname, user, and password in the config/dbase.config.php file 
4. I visit the url **http://loclahost/agouti/public** 
5. I get a blank Page!!! 

Could you please give me some more instructions how to install it properly as i want to contribute on your project ? 

PS: I run php 7.4 on my local server

Thanks in advance

**Comment by evgip** [comment]
You may need to enable error output to provide more information.
To do this, in the file: `start.hleb.php`

Change line 24 from:
```php
define ('HLEB_PROJECT_DEBUG', false);
```
on:
```php
define ('HLEB_PROJECT_DEBUG', true);
```
Next, you can create a host like: dev.loc 

Which uses the `public` folder as public. This can help: 
https://blog.quickadminpanel.com/laravel-public-folder-how-to-configure-domains-for-in-apachenginx/

**Comment by greatdesign** [comment]
Still cant log any error !! :(

**Comment by greatdesign** [comment]
now i have something: 

![Screenshot 2021-11-25 at 17-56-49 Screenshot](https://user-images.githubusercontent.com/46397204/143472483-bdd5c4f4-820c-445b-8f2c-ad61722daaf9.png)

**Comment by evgip** [comment]
Perhaps you haven't configured the `public` folder for the project? Do you see the URL domain that you created as local, for example, dev.loc if you place a regular `index.html` file in the `public` folder? 

The error log is located at this address: `/storage/logs/`

You can use the `master` branch rather than the latest release files, these files are more current. 

Discord: https://discord.gg/dw47aNx5nU
